function [ y ] = onBlackList( x )
%UNTITLED8 Summary of this function goes here
%   Detailed explanation goes here

bl = {'Allston Green District - Griggs St at Commonwealth Ave', ...
  'B.U. Central - 725 Comm. Ave.', ...
  'S Huntington Ave at Heath St', ...
  'Oak Square - 615 Washington St', ...
  'Brighton Center - Washington St at Cambridge St', ...
  'Longwood Ave at Binney St', ...
  'Green Street T Stop - Green St at Amory St', ...
  'Curtis Hall - South St at Centre St', ...
  'Hyde Square - Barbara St at Centre St', ...
  'Washington St at Egremont Rd', ...
  'Washington St at Brock St', ...
  'Commonwealth Ave at Kelton St', ...
  'Commonwealth Ave at Chiswick Rd', ...
  'Harvard Ave at Brainerd Rd', ...
  'Cleveland Circle', ...
  'Williams St at Washington St', ...
  'Centre St at Seaverns Ave', ...
  'Commonwealth Ave at Agganis Way', ...
  'Agganis Arena - 925 Comm Ave.', ...
  'Curtis Hall at South Street', ...
  'Longwood Ave / Binney St', ...
  'Brighton Center', ...
  'Green St T', ...
  'Allston Green District - Commonwealth Ave & Griggs St', ...
  'Hyde Square at Barbara St', ...
  'Heath St at South Huntington', ...
  'Oak Square YMCA', ...
  'Commonwealth Ave at Buick St', ...
  'Allston Green District - Griggs St at Commonwealth Ave TEMPORARY WINTER LOCATION'
  };

if ismember(x, bl)
  y = 1;
else
  y = 0;
end

end

