function [ y ] = onWhiteList( x )
%UNTITLED8 Summary of this function goes here
%   Detailed explanation goes here

bl = {'Beacon St at Tappan St', ...
  'Coolidge Corner - Beacon St at Centre St', ...
  'Brookline Village - Pearl Street at MBTA', ...
  'Commonwealth Ave At Babcock St', ...
  'Tappan St at Brookline Hills MBTA', ...
  'St Mary''s', ...
  'Cypress St at Clark Playground', ...
  'Brookline Town Hall', ...
  'JFK Crossing at Harvard St. / Thorndike St.', ...
  'Coolidge Corner - Beacon St @ Centre St', ...
  'Brookline Village - Station Street @ MBTA', ...
  'Washington Square at Washington St. / Beacon St.', ...
  'Brookline Village - Station Street @ MBTA TEMPORARY WINTER LOCATION', ...
  'Washington Square at Washington St. / Beacon St. TEMPORARY WINTER LOCATION', ...
  };

if ismember(x, bl)
  y = 1;
else
  y = 0;
end

end

